name: python 

on:
  workflow_dispatch: # يتيح لك تشغيل الـ Workflow يدوياً بزر Run workflow

jobs:
  sshx-runner:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Curl & Launch SSHX
        run: |
          echo "Starting SSHX Session..."
          curl -sSf https://sshx.io/get | sh -s run
